// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vUAAVLxK9p8YVDtkSK8uqiF_tdNYy2c',
    appId: '1:136040140837:web:8dd45ea6a1bd88e0126fcc',
    messagingSenderId: '136040140837',
    projectId: 'my-project-c6e43',
    authDomain: 'my-project-c6e43.firebaseapp.com',
    storageBucket: 'my-project-c6e43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKzbzHUbsxIzGbJRD0bwEZ-pyoyewmlBY',
    appId: '1:136040140837:android:a02e6fda68bbd99d126fcc',
    messagingSenderId: '136040140837',
    projectId: 'my-project-c6e43',
    storageBucket: 'my-project-c6e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArSIIUb_87fwJIxTY2viTJ2SrT_bctDGU',
    appId: '1:136040140837:ios:c3a7f1111df18be7126fcc',
    messagingSenderId: '136040140837',
    projectId: 'my-project-c6e43',
    storageBucket: 'my-project-c6e43.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArSIIUb_87fwJIxTY2viTJ2SrT_bctDGU',
    appId: '1:136040140837:ios:707e2c5ad9970535126fcc',
    messagingSenderId: '136040140837',
    projectId: 'my-project-c6e43',
    storageBucket: 'my-project-c6e43.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
